// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI_StudentList.Data;

#nullable disable

namespace WebAPI_StudentList.Migrations
{
    [DbContext(typeof(StudentListContext))]
    [Migration("20250305023327_DbInit")]
    partial class DbInit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebAPI_StudentList.Data.Faculty", b =>
                {
                    b.Property<string>("MaKhoa")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenKhoa")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaKhoa");

                    b.ToTable("Faculty");
                });

            modelBuilder.Entity("WebAPI_StudentList.Data.Student", b =>
                {
                    b.Property<string>("MaSinhVien")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaKhoa")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenSinhVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaSinhVien");

                    b.HasIndex("MaKhoa");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("WebAPI_StudentList.Data.Student", b =>
                {
                    b.HasOne("WebAPI_StudentList.Data.Faculty", "MaKhoaNavigation")
                        .WithMany("SinhVien")
                        .HasForeignKey("MaKhoa");

                    b.Navigation("MaKhoaNavigation");
                });

            modelBuilder.Entity("WebAPI_StudentList.Data.Faculty", b =>
                {
                    b.Navigation("SinhVien");
                });
#pragma warning restore 612, 618
        }
    }
}
